version: "3.9"
services:
  imageservice:
    build: .
    depends_on:
      - imageservice-mysql
    ports:
      - "8001:8001"
    environment:
      DB_URL: imageservice-mysql:3306/imageservice-mysql
      DB_USER: developer
      DB_PASS: password
  imageservice-mysql:
    image: "mysql:latest"
    container_name: imageservice-mysql
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imageservice-mysql
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_HOST: '%'
    ports:
      - "3309:3306"
volumes:
  db_mysql:
